arklexai/Agent-First-Organization

docs/docusaurus.config.js
Use "ArkLex" as the name for now.
@luyunan0404
=> update name to ArkLex

arklex/evaluation/get_documents.py, arklex/orchestrator/task_graph.py, model_api.py
1. Fix global intents
2. Rename the package name
=> Fix global intents

docs/docusaurus.config.js
=> fix home page sub title

docs/src/css/custom.css, docs/src/pages/index.js
=> docs: add video in home

docs/docs/intro.md, docs/src/pages/index.js
=> docs: center paragraph

docs/src/css/custom.css, docs/src/pages/index.js
=> docs: update margin

docs/docs/tutorials/customer-service.md
=> add customer-service tutorial video

pyproject.toml, requirements.txt
=> remove uvloop

.github/pull_request_template.md, .github/workflows/pr-check.yml
- What is this PR about? Provide a clear, concise summary.
Added PR template and description validation check to enforce better documentation standards in pull requests.
- copy the task/doc link if any.
None
- Why is this change needed?
We need to ensure all PRs have proper documentation and testing information
- How does this change solve the problem?
Added two files:
PR template with structured sections for Summary, Description, and Tests
GitHub Action workflow to validate PR descriptions have sufficient content
- What side effects might this change have?
All PRs will now require meaningful descriptions and test documentation
- @xinyang-articulate
=> create pr template

docs/src/components/HomepageFeatures/styles.module.css, docs/src/pages/index.module.css
This PR addresses the issue of content misalignment on larger screens by adjusting the layout styling.
The issue was causing certain elements to appear misaligned when viewed on larger screens, affecting the user experience.
@KathyLiu20
=> fix: resolved alignment issue on larger screens

arklex/env/workers/worker.py, arklex/orchestrator/orchestrator.py, arklex/utils/graph_state.py
This PR is to initialize `message_state` before entering the while loop.
In the current orchestrator file, message_state can be initialized only in the while loop. However, if there is an error with the while loop, message_state will not be defined and cause an error when trying to context generation. Therefore, we would like to initialize the it before entering the while loop.
- Run Shopify bot in local hub
- Run customer service sample taskgraph
@luyunan0404
=> init message state

arklex/env/tools/shopify/get_web_product.py, arklex/orchestrator/orchestrator.py, arklex/orchestrator/task_graph.py, arklex/utils/graph_state.py, examples/multiple_choice/taskgraph.json, examples/multiple_choice/test.py, examples/multiple_choice/test_cases.json
This PR is to fix the multiple choice function.
The multiple choice function broke after the orchestrator retructure, and this PR is to fix its function and return it as a direct message.
- Test the Shopify bot in local hub
- Test multiple choice in local hub
@luyunan0404
=> fix multiple choice

arklex/__init__.py, pyproject.toml
This PR is to change the version-update method from static verison number to dynamic one from package setup.
This PR is to change the version-update method from static verison number to dynamic one from package setup.
Test case 1: PR check
Test case 2: Integration test for PR
- @luyunan0404
=> update package version method

arklex/__init__.py
The PR is to update the package version from 0.0.12-rc.1 to 0.0.12.
The PR is to update the package version from 0.0.12-rc.1 to 0.0.12, and only package version number is changed.
Since the PR is only about package version update, there is no test needed.
@luyunan0404
=> package version update to 0.0.12

arklex/__init__.py, arklex/env/tools/utils.py, arklex/memory/__init__.py, arklex/memory/core.py, arklex/memory/prompts.py, arklex/memory/test/teststm.py, arklex/orchestrator/orchestrator.py, arklex/utils/graph_state.py
Separates STM logic into a ShortTermMemory class and helper functions.
Supports following features:
- Personalizes user intent
- Retrieve relevant memory records based on a weighted similarity score.
- Retrieve the most relevant past intent.
Improves encapsulation and makes memory easier to test and extend.
- Why is this change needed?
We lacked a mechanism to determine context of user query with earlier conversation trajectory.
- How does this change solve the problem?
We can now store the complete trajectory and encapsulate it in short term memory.
- What side effects might this change have?
- We might want to test the spersonalization for other cases
Validated orchestrator can use the new ShortTermMemory class without changes in logic
Validated retrieval and intent personalization with …
=> added stm with intent personalization

pyproject.toml, requirements.txt
Add fixed package version to be installed when installing the package.
The open-source code has package version range defined in `pyproject.toml` file. However, for business usage, there can be other packages to be installed, so it is better to have a fixed version which can guarantee compatability with the current framework.
Run package installation and hub to test the chat feature, and the package version is fixed.
@luyunan0404 
@yongwhan
=> add fixed required package version when installing

create.py, eval.py, model_api.py, run.py
- add annotations to Python files in root directory.
- to improve the code quality, add annotations to Python files in root directory in `Agent-First-Organization` GitHub repository.
=> feat: fix annotations on root directory

tests/test_resources.py, tests/utils/utils.py, tests/utils/utils_tools.py, tests/utils/utils_workers.py
- add annotations to Python files in tests directory.
- to improve the code quality, add annotations to Python files in tests directory in `Agent-First-Organization` GitHub repository.
=> feat: fix annotations on tests directory

examples/calendar/test.py, examples/hitl_server/test.py, examples/hubspot/test.py, examples/multiple_choice/test.py, examples/shopify/test.py, examples/shopify/user_attr_api.py
- add annotations to Python files in `examples` directory.
- to improve the code quality, add annotations to Python files in `examples` directory in `Agent-First-Organization` GitHub repository.
=> feat: fix annotations on examples directory

benchmark/tau_bench/auto_error_identification.py, benchmark/tau_bench/run.py, benchmark/tau_bench/tau_bench_eval.py, benchmark/tau_bench/tau_bench_result_analysis.py
- add annotations to Python files in `benchmark/tau_bench` root directory.
- to improve the code quality, add annotations to Python files in `benchmark/tau_bench` root directory in `Agent-First-Organization` GitHub repository.
=> feat: fix annotations on benchmark/tau_bench root directory

benchmark/tau_bench/agents/agent_first_org.py, benchmark/tau_bench/agents/tool_calling_agent.py
- add annotations to Python files in `benchmark/tau_bench/agents` directory.
- to improve the code quality, add annotations to Python files in `benchmark/tau_bench/agents` directory in `Agent-First-Organization` GitHub repository.
=> feat: fix annotations on benchmark/tau_bench/agents directory

arklex/env/env.py, arklex/env/nested_graph/nested_graph.py, arklex/env/planner/react_planner.py, arklex/env/planner/test/test_shopify_advanced.py, arklex/env/planner/test/test_shopify_simple.py, arklex/env/prompts.py
- add annotations to Python files in `arklex/env` planner, nested_graph, and root directories.
- to improve the code quality, add annotations to Python files in `arklex/env` planner, nested_graph, and root directories in `Agent-First-Organization` GitHub repository.
=> feat: fix annotation on arklex/env/planner, nested_graph, and root directories

arklex/env/env.py, arklex/env/nested_graph/nested_graph.py, arklex/env/planner/react_planner.py, arklex/env/planner/test/test_shopify_advanced.py, arklex/env/planner/test/test_shopify_simple.py, arklex/env/prompts.py, arklex/env/tools/hubspot/_exception_prompt.py, arklex/env/tools/hubspot/check_available.py, arklex/env/tools/hubspot/create_meeting.py, arklex/env/tools/hubspot/create_ticket.py, arklex/env/tools/hubspot/find_contact_by_email.py, arklex/env/tools/hubspot/find_owner_id_by_contact_id.py, arklex/env/tools/hubspot/utils.py
- add annotations to Python files in `arklex/env/tools/hubspot`.
- to improve the code quality, add annotations to Python files in `arklex/env/tools/hubspot` in `Agent-First-Organization` GitHub repository.
=> feat: fix annotation on arklex/env/tools/hubspot directory

arklex/env/tools/hubspot/_exception_prompt.py, arklex/env/tools/hubspot/check_available.py, arklex/env/tools/hubspot/create_meeting.py, arklex/env/tools/hubspot/create_ticket.py, arklex/env/tools/hubspot/find_contact_by_email.py, arklex/env/tools/hubspot/find_owner_id_by_contact_id.py, arklex/env/tools/hubspot/utils.py
- For each file in hubspot directory, put comments, as relevant.
- For each file in hubspot directory, put comments, as relevant.
- This should be a no-op; so, it does not require testing.
- @Lingxiao-Chen-arklex
=> feat: add comments to each file in hubspot directory

arklex/env/tools/acuity/_exception_prompt.py, arklex/env/tools/acuity/book_info_session.py, arklex/env/tools/acuity/cancel.py, arklex/env/tools/acuity/get_apt_by_email.py, arklex/env/tools/acuity/get_available_dates.py, arklex/env/tools/acuity/get_available_times.py, arklex/env/tools/acuity/get_session_types.py, arklex/env/tools/acuity/get_type_id_by_apt_name.py, arklex/env/tools/acuity/reschedule.py, arklex/env/tools/acuity/utils.py
- Add annotations to every files in `arklex/env/tools/acuity` to improve the code quality.
- Add annotations to every files in `arklex/env/tools/acuity` to improve the code quality.
- This PR should be a no-op, but I will add `run-integration-tests` flag as a label, just to be sure!
- @Lingxiao-Chen-arklex
=> feat: add annotations to files in arklex/env/tools/acuity

arklex/env/env.py, arklex/env/prompts.py, arklex/env/tools/custom_tools/http_tool.py, arklex/env/tools/hubspot/check_availability.py, arklex/env/tools/hubspot/check_available.py, arklex/env/tools/hubspot/create_meeting.py, arklex/env/tools/hubspot/create_ticket.py, arklex/env/tools/hubspot/find_contact_by_email.py, arklex/env/tools/hubspot/find_owner_id_by_contact_id.py, arklex/env/tools/utils.py, arklex/utils/graph_state.py, arklex/utils/model_provider_config.py, arklex/utils/slot.py, arklex/utils/utils.py, eval.py, model_api.py
- Put all missing annotations/comments for each file in the repo that is missing them, except tools/shopify.
- To improve the code quality, adding missing annotations/comments would be good.
- This PR should be a `no-op`, not requiring a test, as each edit is adding a comment/docstring.
- @xinyang-articulate
=> feat:put all missing annotations/comments, except tools/shopify directory.

arklex/__init__.py
This PR is to update package version to a new release candidate version `0.0.15-rc.1`
This PR is to update package version to a new release candidate version `0.0.15-rc.1`
There is no need to do test and it is only about updating the package version
@yongwhan
=> update package version

arklex/orchestrator/NLU/core/intent.py, arklex/orchestrator/task_graph.py
Fix problems introduced by intent detection and add more logs
- Fix the broken taskgraph when `intent=null`
- Fix the broken intent detection when there is `)` in the defined intent
Test two cases above and there would not be an error any more.
@yongwhan 
@luyunan0404
=> fix parenthesis in intent detection and None intent

arklex/env/env.py, arklex/env/tools/shopify/cart_add_items.py, arklex/env/tools/shopify/find_user_id_by_email.py, arklex/env/tools/shopify/get_cart.py, arklex/env/tools/shopify/get_order_details.py, arklex/env/tools/shopify/get_products.py, arklex/env/tools/shopify/get_user_details_admin.py, arklex/env/tools/shopify/get_web_product.py, arklex/env/tools/shopify/return_products.py, arklex/env/tools/shopify/search_products.py, arklex/env/tools/tools.py, arklex/orchestrator/NLU/core/slot.py, arklex/orchestrator/NLU/services/model_service.py, arklex/orchestrator/NLU/utils/formatters.py, arklex/utils/exceptions.py
This PR fixed errors related to slotfilling API and exception class
- There is an additional parameter called `api_service` to pass.
- Add back exception class defined in `arklex/utils/exceptions.py`.
- Add `extra_message` for tool execution errors.
- Test Shopify slotfilling function
- Test Shopify tool calling function
- Test in hub
@Saravanan1999 
@luyunan0404 
@yongwhan
=> fix: slotfilling API and exception class

arklex/__init__.py
update package version to 0.0.17
update package version to 0.0.17 based on 0.0.16 and fixed errors.
There is no tests needed because this is only for package version update
@yongwhan
=> update package version to 0.0.17

arklex/env/tools/hubspot/utils.py, arklex/env/tools/types.py, docs/docs/Integration/Hubspot.md, examples/hubspot/taskgraph.json
The Hubspot agent was no longer working due to an error when registering the Hubspot tools. 
Why is this change needed?
- Hubspot agent was broken 
How does this change solve the problem?
- Added the missing code from the `chatbots` repo
- Plus, removed outdated code from Hubspot taskgraph
What side effects might this change have?
-- None 
Pre-commit code format check: Run `pip install pre-commit` and `pre-commit install` before committing changes 
@xinyang-articulate
@luyunan0404
@yongwhan
=> Fixed minor issue with hubspot tools

.github/pull_request_template.md
- Change frontend pull request template so that not everyone from devs receive the email notification.
- To improve the target devs who are receiving email notifications
- This PR probably does not require a testing since it should be a more or less a no op.
=> feat: update pull_request_template.md

.github/workflows/lint.yml
- This PR re-enables the `lint.yml` GitHub Actions workflow to fix existing linter errors. Re-enabling this workflow will help ensure consistent code formatting and catch linting issues early during pull requests.
- The changes restore the linting workflow (`lint.yml`) that runs Ruff on Python files during pull requests. This workflow enforces consistent code style and detects common coding errors before merging. Maintaining this automated linting process improves overall code quality and reduces manual code review overhead.
=> feat: enable linter

arklex/__init__.py
This is a PR to update the package version from 0.0.18-rc.3 to 0.0.18-rc.4
This is a PR to update the package version from 0.0.18-rc.3 to 0.0.18-rc.4
This is a trivial change and no test is needed for the change.
=> package version update

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE.md
- Create a doc on how to contribute to the codebase.
- Create a doc on how to contribute to the codebase.
- This should not need a test as a simple `md` document.
=> feat: create CONTRIBUTING.md and CODE_OF_CONDUCT.md

docs/README.md
This PR is to fix the README of documentation for deploying doc on website
This PR is to fix the README of documentation for deploying doc on website
Since there is only trivial change in the readme file, there is no need to add integration test
=> fix documentation readme

README.md
- Update README.md with a hardcoded overall test coverage number, which is 99.1% right now.
- Update README.md with a hardcoded overall test coverage number, which is 99.1% right now.
=> feat: update README.md with a hardcoded overall test coverage number

.github/workflows/test-coverage.yml, README.md
- Create a badge in README after the test coverage run
- Create a badge in README after the test coverage run
=> feat: create a badge in README after the test coverage run

.github/workflows/reusable-run-coverage-tests.yml
- Fixing the nightly by fixing `reusable-run-coverage-tests.yml` file to follow `test-coverage.yml` file.
- Fixing the nightly by fixing `reusable-run-coverage-tests.yml` file to follow `test-coverage.yml` file.
=> feat: update reusable-run-coverage-tests.yml

.github/workflows/nightly-regression.yml
- From the nightly run, it seems like there is a small bug that needs to be fixed. So, let's fix that.
- From the nightly run, it seems like there is a small bug that needs to be fixed. So, let's fix that.
=> bug: disallow README update

project_improvements/ARCHITECTURE_IMPROVEMENTS.md, project_improvements/CODE_QUALITY_IMPROVEMENTS.md, project_improvements/COMPREHENSIVE_IMPROVEMENTS_SUMMARY.md, project_improvements/DEPLOYMENT_IMPROVEMENTS.md, project_improvements/DOCUMENTATION_IMPROVEMENTS.md, project_improvements/PERFORMANCE_IMPROVEMENTS.md, project_improvements/SECURITY_IMPROVEMENTS.md, project_improvements/TECHNICAL_DEBT_ROADMAP.md, project_improvements/TESTING_IMPROVEMENTS.md
- Create 3 md files for future improvements.
- I will come back to these lists and maintain them for future work.
- Create 3 md files for future improvements.
- I will come back to these lists and maintain them for future work.
=> feat: create md files for future improvements

.github/workflows/nightly-regression.yml
- Update `nightly-regression.yml` to include an email notification for both failed and succeeded instances
- Update `nightly-regression.yml` to include an email notification for both failed and succeeded instances
=> feat: Update nightly-regression.yml (attempt #2)

.github/workflows/nightly-regression.yml
- Revert Updating `nightly-regression.yml` to include an email notification for both failed and succeeded instances
- Revert Updating `nightly-regression.yml` to include an email notification for both failed and succeeded instances
=> bug: revert updating nightly-regression.yml: attempt #3 to follow.

README.md, arklex/env/tools/RAG/build_rag.py, arklex/orchestrator/NLU/services/model_service.py, tests/env/agents/test_agent.py, tests/env/test_env.py, tests/env/tools/RAG/test_build_rag.py, tests/env/tools/test_booking_db_tools.py, tests/env/tools/test_database_build_database.py, tests/env/tools/test_database_utils.py, tests/evaluation/test_get_documents.py, tests/orchestrator/NLU/services/test_model_service.py, tests/orchestrator/generator/test_generator_coverage.py, tests/orchestrator/generator/test_main_generator.py
- increase the test coverage so that it is `99%+`; working on a higher one in the subsequent PR.
- increase the test coverage so that it is `99%+`; working on a higher one in the subsequent PR.
=> feat: increase test coverage, to pass run-coverage-tests

arklex/env/env.py, tests/env/test_env.py
Fix - Replaced passing raw attributes with properly constructed slot objects to ensure correct slot filling, chat flow, and tool execution.
- The slot filling mechanism expects a list of slot objects, each with specific fields such as name, type, required, etc. Passing raw attributes or an improperly structured list can result in missing or malformed slot objects, causing the slot filling process to fail or behave unpredictably.
- Tools that depend on the presence and correctness of slot values may receive incomplete or invalid data, leading to runtime errors, failed API calls, or incorrect business logic execution.
- This PR fixes this issue
=> api: fix slots

arklex/__init__.py, pyproject.toml
This PR is to fix the redis version conflict issue and add a fixed version of redis for control.
This PR is to fix the redis version conflict issue and add a fixed version of redis for control.
Tested in the requirements file for package installation and it worked well.
=> fix redis version

arklex/__init__.py, arklex/env/env.py, arklex/orchestrator/NLU/entities/slot_entities.py, arklex/orchestrator/task_graph/task_graph.py
This change fixes execution of http_tool used in NLU flow and OpenAI text agent flow.
=> fix: consistent http tool resource

.github/workflows/reusable-taskgraph-generation-validation.yml, arklex/env/agents/multi_agent.py, arklex/env/agents/patterns/agents_as_tools.py, arklex/env/agents/patterns/base_pattern.py, arklex/env/agents/patterns/deterministic.py, arklex/env/agents/patterns/llm_as_a_judge.py, arklex/env/agents/patterns/parallelization.py, arklex/env/agents/utils/agent_loader.py, arklex/env/env.py, arklex/orchestrator/generator/core/generator.py, arklex/utils/mysql.py, create.py, examples/test/config.json, tests/env/agents/test_agent_utils.py, tests/env/agents/test_multi_agent.py, tests/env/test_env.py, tests/orchestrator/generator/formatting/taskgraph_format_checker.py
Attempts to fix the integration tests and broken build create_taskgraph
- What is this PR about? Provide a clear, concise summary.
- copy the task/doc link if any.
- Why is this change needed?
Needed to ensure healthy build pipeline
- How does this change solve the problem?
Fixes the breaking tests and build
- What side effects might this change have?
None
=> fix: fix integration tests and build fail

arklex/__init__.py, arklex/env/env.py, arklex/env/workers/hitl/entities.py, arklex/env/workers/hitl/hitl_worker.py, arklex/orchestrator/task_graph/task_graph.py
Package minor version update release.
- Upgrade package version from 0.0.x to 0.1.x
- Fix human-in-the-loop worker response
- Remove node weights when doing random selection
- Test taskgraph migration with `jump_to_node` function
- Test human in the loop worker
@shehan360
=> Release 0.1.0

arklex/env/tools/RAG/retrievers/faiss_retriever.py, arklex/env/tools/RAG/retrievers/milvus_retriever.py, arklex/env/tools/utils.py, arklex/env/workers/message/message_worker.py, arklex/env/workers/milvus_rag/milvus_rag_worker.py, arklex/env/workers/rag_message/rag_message_worker.py, examples/test/config.json, tests/env/tools/test_utils.py
Fix source document format after doing Milvus retriever
Fix source document format after doing Milvus retriever, and add record to trajectory.
- Test frontend source display function
- Test source documents in trajectory
=> fix: milvus retriever source

arklex/__init__.py, arklex/env/agents/openai_realtime_agent.py, arklex/env/tools/tools.py
Fix tool initialization and add log to realtime agent input
Fix tool initialization and add log to realtime agent input to capture runtime error
- Test tools with defined slots (causing tool initialization failure)
- Test tool registration
=> fix: tool initialization

arklex/orchestrator/NLU/core/slot.py, arklex/orchestrator/NLU/services/model_service.py
This PR addresses the issue where the retriever was unable to connect to the model service due to incorrect method signatures. 
This PR addresses the issue where the retriever was unable to connect to the model service due to incorrect method signatures.
=> api: Fix/retriever model service issue

arklex/__init__.py, arklex/env/workers/message/message_worker.py, arklex/orchestrator/orchestrator.py, arklex/orchestrator/post_process.py
Fix link post processing which removes existing links
This PR is to fix the link post-processing function, which will remove existing link even if it appears in the context (for `message-worker`)
- Test message worker response, existing links will not be removed
- Test RAG worker response, existing links will not be removed
=> fix link postprocess

arklex/__init__.py, arklex/env/agents/openai_realtime_agent.py, arklex/orchestrator/task_graph/task_graph.py
This PR fixes the issue where agent does not speak after the agent handover.
This issue seems to be coming from openai side.
https://github.com/openai/openai-python/issues/2607
@xinyang-articulate
=> fix agent not speaking after handover

arklex/env/tools/custom_tools/retriever.py
Fixes the retriever for the realtime voice agent
Changes from the PR: https://github.com/arklexai/Agent-First-Organization/pull/308 has broken the realtime voice agent's retriever. This reverts the changes to temporarily fix the retriever.
@xinyang-articulate
=> fix retriever for realtime agent

arklex/__init__.py, arklex/orchestrator/task_graph/task_graph.py
Fix a case where start_agent_data is null
Fix a case where start_agent_data is missing data to initialize the realtime voice agent
=> fix start agent data

arklex/env/env.py, arklex/env/tools/RAG/retrievers/milvus_retriever.py, arklex/env/workers/milvus_rag/entities.py, arklex/env/workers/milvus_rag/milvus_rag_worker.py, arklex/env/workers/rag_message/entities.py, arklex/env/workers/rag_message/rag_message_worker.py, arklex/orchestrator/entities/orchestrator_state_entities.py
Remove DB operations in Milvus-related workers
Remove DB operations in Milvus-related workers and pass in directly
- Test Milvus-RAG worker
- Test RAG Message worker
- Test them in real applications
@shehan360
=> Remove DB operations in Milvus-related workers

.github/workflows/test-live-pipeline.yml, .github/workflows/test-mock-pipeline.yml, integration_tests/mock_tests/test_worker_taskgraph.py, integration_tests/run.sh, integration_tests/utils/vector_database/standalone_milvus.sh
Fix integration tests execution logic
- Stop execution when any error occurs
- Inherit LLM API key
- Fix Milvus running by Docker
- Check test failure case which fails the pipeline
- Check test pass case which finishes the pipeline
@shehan360 
@KathyLiu20
=> fix integration tests
