create.py
examples/customer_service/taskgraph.json
examples/shopify/taskgraph.json
run.py

NLU automate api start/terminate failed so that user intent detection failed, lead to "others" intent which will be hard for debugging unless open Logger Info. 
The current fix is using function calling instead of API calling to do the NLU.

remove NLU api to call function directly

---

arklex/orchestrator/orchestrator.py
benchmark/tau_bench/agents/agent_first_org.py
benchmark/tau_bench/tau_bench_eval.py

This PR includes the following changes:
- Fix: `arklex/orchestrator/orchestrator.py` Updated  to fix key error issues when indexing DefaultWorker and MessageWorker. 
- Fix: `benchmark/tau_bench/tau_bench_eval.py` Randomize default task selection in tau bench evaluation.
- Feature: `benchmark/tau_bench/agents/agent_first_org.py` Append metadata to tau_bench evaluation result.

Append metadata to tau_bench_evaluation result

---

README.md
arklex/utils/model_provider_config.py
create.py
docs/docs/Config/ChatModels.md

Added support for task graph generation with more LLM providers(i.e. Gemini and Anthropic)
- Task: [https://www.notion.so/arklex/Taskgraph-Generation-with-Gemini-Anthropic-1c82ad77209380328245ca694cd44a82](https://www.notion.so/1c82ad77209380328245ca694cd44a82?pvs=21)
- Added to existing documentation(Taskgraph section): [https://www.notion.so/arklex/LLM-Integration-Documentation-1a32ad7720938061b259e44a03ac72ec](https://www.notion.so/1a32ad7720938061b259e44a03ac72ec?pvs=21)
- Why: Need to make multiple LLM providers compatible with the dev tool. An important & critical step is being able to generate the task graph.
- How: Made updates to the following files:
- **docs/docs/Config/ChatModels.md**: added documentation for taskgraph generation for Gemini & Anthropic
- **README.md**: added …

Taskgraph generation with Gemini/Anthropic

---

arklex/orchestrator/orchestrator.py

Disable the `skip_node` function (check whether node limit <= 0, if yes, skip the current node) after taskgraph navigation.
Disable the `skip_node` function may cause the case of not skipping a node (when actually should), but it is better than skipping a node (when should not).
- Run the Shopify bot in local hub settings
- Run the dev tool customer service sample taskgraph
@luyunan0404

disable skip node

---

arklex/env/tools/tools.py

- add tool's input and output even though it doesn't extract all the slots for execution
- Previously, when the slots of a tool hasn't been extracted completely, the slots and response of the tool won't be added into the trajectory, which causing incomplete information when do the evaluation analysis. 
- Now all the slots and response result will be saved into the trajectory no matter whether successfully execute.
- @ryanshea10

Add tool's input/output for Incomplete trajectory 

---

.github/workflows/test-resources.yml

Disable the integration test before merging a PR to the main branch.
The integration test currently incurs additional cost, and should be able to use cheaper models to save the cost
This change has no impact on the current workflow and does not affect the logic
@luyunan0404

disable test files

---

arklex/orchestrator/task_graph.py

The PR is to modify the global intent switch logic in the current taskgraph.
For the global intent prediction, if it is the same as the last turn
- The node is the leaf node: it could re-enter the same global intent
- The node is not the leaf node: it should continue the current global intent instead of re-entering
- Tested the global intent switch where the node is leaf node and it will re-enter the same intent
- Tested the global intent switch where the node is not leaf node and it will continue the current task
@luyunan0404 
@luigi617

allow global intent re-enter if leaf node

---

arklex/env/env.py
arklex/env/tools/RAG/retrievers/milvus_retriever.py
arklex/env/workers/milvus_rag_worker.py
arklex/env/workers/rag_message_worker.py
arklex/env/workers/worker.py
arklex/orchestrator/orchestrator.py
arklex/orchestrator/task_graph.py
arklex/utils/graph_state.py
examples/milvus_filter/taskgraph.json

The PR is to add tags when using Milvus vector database for crawling and RAG
- Add a Milvus operation to update tags for given `qa_doc_id`
- Pass in tags as an additional args when executing the `MilvusRagWorker` and `RagMsgworker` (can be expanded to other use cases)
- Tag with be used as a filter to get relevant docs (only docs with the same tag will be searched)
When a hard-coded tag is applied to a RAG node, only docs with the tag will be returned as rouce.
@luyunan0404

add milvus tag for rag

---

arklex/env/workers/faiss_rag_worker.py
arklex/env/workers/hitl_worker.py
arklex/env/workers/message_worker.py
arklex/env/workers/search_worker.py

The PR https://github.com/arklexai/Agent-First-Organization/pull/100 is about adding tags to Milvus-related workers. Other workers should be able to parse the tags input even not using it.
The default execution method of worker should handle tag input even if not using it
Logs from DataDog:
https://us5.datadoghq.com/logs?query=host%3Ai-06db748c8297c5aea%20service%3Aqa-server-bot%20container_id%3A128d5ea8a9451146c0d10b6c29d94caaee8cab031c9c656b7c48d2df474b5ff6%20filename%3A0.log&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZa3x_VjAACast5xbo-0PQAb&event=&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AwAAAZa3x-donTTrogAAABhBWmEzeF9WakFBQ2FzdDV4Ym8tMFBRQWwAAAAkMDE5NmI4NTktOTE5Zi00ZTE0LWIwYjEtNWYwZmMxMzdkMjM …

fix tags for workers

---

arklex/env/tools/hubspot/check_available.py

- This PR mainly focuses on fixing the bugs brought from retrieving meeting links. 
- I have changed the logic to check whether the response is good or not because the structure of the error response is different depending on the situations.
- On the staging hub, the testing result is unstable. Four out of five tests are passed but only one failed due to the previous issue. 
- I made sure every cases in my consideration to raise the tool failure errors.
- The error messages I have encountered have various structures. To be honest, I am not sure whether I included all cases. But I have tried stricter logical check, I think it should be good.
- @xinyang-articulate @yongwhan

Fix the problem of retrieving the meeting_links

---

arklex/orchestrator/task_graph.py

- Fix the issue of not switching nodes from different intents
- Modification on task_graph.py
- It is urgent to switch the node when user has different intent
- Change the logical check
- @xinyang-articulate @yongwhan

Fix the error of unable to switch the nodes from different intents

---

arklex/evaluation/simulate_first_pass_convos.py
arklex/orchestrator/task_graph.py
eval.py

- Update the user simulator to generate conversation with id so that the generated conversation with the same profile has the same id instead of getting random sequence from multithread
- When rerun the user simulator with the same profiles but updated taskgraph config, we want to compare the matching performance. 
- Assign id for the profile and corresponding generated conversation. As long as the profile doesn't change, the conversation_id will be the same.
- For all the unknown intent, assign "others" (which is the unsure intent).
- Doesn't affect the core Agent response functionality.
- @xinyang-articulate

update user simulator

---

arklex/env/env.py
arklex/env/prompts.py
arklex/env/tools/hubspot/check_availability.py
arklex/env/tools/hubspot/create_meeting.py
arklex/env/tools/utils.py
arklex/env/workers/message_worker.py
arklex/orchestrator/orchestrator.py
arklex/types.py
arklex/utils/graph_state.py
arklex/utils/slot.py

- FIrstly, there are new prompts specific for a "speech" stream that will help in generating responses that are suitable for voice bots. 
- Secondly, there is another hubspot tool, to check the availability of **any** representative for a meeting 
- The new prompts are required to reduce the verbosity of reponses generated by a voice bot
- Using `steam_type`, we switch between `TEXT` stream prompts and `SPEECH` stream prompts
- By prompting for speech friendly responses, we can get the desired type of responses for speech streams
- The `check_availability` tool simplifies the use of 3 existing hubspot tools (`find_contact_by_email`, `find_owner_id_by_contact_id`, `check_available`)
- The `create_meeting` tool has been modified to prompt for the customer's first and last name, and email …

Add prompts for voice bot support and fix hubspot tool integration

---

arklex/env/workers/hitl_worker.py

The tag as an additional args will cause an error for the HITL worker.
The tag as an additional args will cause an error for the HITL worker.
This is a standalone component (HITL worker) in the package and should not impact other functions.
@yongwhan

fix hitl tag error

---

.github/workflows/test-resources.yml

- Updated the pytest command to include the coverage arguments: --cov=arklex --cov-report=term-missing --cov-report=html --no-cov-on-fail
- Explicitly added pytest-cov to the dependencies installation step to ensure it's available in the GitHub Actions environment.
- These changes should resolve the error I am seeing in GitHub Actions [here](https://github.com/arklexai/Agent-First-Organization/actions/runs/15688570494/job/44197878089#step:5:15).
- This should pass as it will now:
- Install pytest-cov explicitly
- Run the tests with coverage reporting enabled
- Generate both terminal and HTML coverage reports
- @xinyang-articulate

feat: update test-resources.yml

---

.github/workflows/test-coverage.yml
pyproject.toml

- Add a GitHub Actions workflow to run tests with coverage reporting on pull requests targeting the main branch.
- Implement soft-blocking on coverage regression by posting PR comments if coverage drops below 98%.
- Upload coverage XML and HTML reports as workflow artifacts for review.
- This change is needed to ensure that test coverage does not regress unnoticed during development and pull requests.
- It solves the problem by automatically running pytest with coverage, comparing coverage against thresholds, and alerting developers via PR comments.
- Coverage reports are also uploaded as artifacts for deeper inspection when needed.
- 
- How does this change solve the problem?
- What side effects might this change have?
- TBD

feat: create test-coverage.yml in github action workflow

---

.github/workflows/test-coverage.yml

- Implement blocking on coverage regression by posting PR comments if coverage drops below 99%.
- This is OK since you can pick `regression-test` label if you do not care about the test coverage.
- This change is needed to ensure that test coverage does not regress unnoticed during development and pull requests.
- TBD

feat: update test coverage threshold to 98.

---

arklex/env/tools/hubspot/check_availability.py
arklex/orchestrator/NLU/utils/formatters.py

- I modified a little in formatter files to make sure every function of hubspot works well. And I found the slotfilling seems to fail.
- Ensure every functions work is essential. 
- Add enum in the context for slotfilling api to consider
- I just ensure the previous problematic function works. And it does consider enum value of the slots now.
- I want to mention that I am not fully aware of how formatter.py works. Currently I only made some changes for the prompt. I cannot guarantee other places to format slot are good.

Fix the issue of slotfilling (does not consider values in enum before)

---

arklex/env/tools/RAG/retrievers/retriever_document.py
arklex/utils/redis.py
pyproject.toml
tests/env/tools/RAG/test_retriever_document.py

- This PR adds the ability to cache the embedded query for the milvus retriever
- Also adds redis utility methods
- We create embeddings with an OpenAI call for every query
- By caching the embeddings, we can retrieve the queries instead of another redundant OpenAI call
- Speeds up retrieving

feat: caching for embedded retriever query 

---

arklex/env/agents/openai_agent.py
arklex/env/prompts.py

- This PR adds changes that support chat and speech streaming when using the openai agent
- Decided by the stream type, the primary differentiator in generated responses will be how the agent is prompted. 
- Chat streaming was not working when using agent
- This change uses event streams to generate and return responses 

fix: OpenAI agent chat streaming

---

arklex/env/tools/RAG/retrievers/milvus_retriever.py
arklex/env/tools/RAG/retrievers/retriever_document.py
tests/env/tools/RAG/test_retriever_document.py

- fixes the issue where documents that were added to the knowledge base were getting cached
- redis is flooded with document embedding caches
- makes caching of the embedding optional
- no side effects, better control on caching embeddings
@arklexai/agent-leads 
@shehan360

cache only the query embedding

---

arklex/__init__.py
arklex/env/tools/hubspot/book_meeting.py

This PR adds a simpler tool for meeting booking with hubspot.
The existing create_meeting tool doesn't work well with the voice agent.

add hubspot book meeting tool

---

arklex/env/agents/openai_agent.py
arklex/orchestrator/NLU/entities/slot_entities.py
tests/env/tools/test_tools.py

This is a fix to get SlotGroups working in OpenAI Agent.
Currently, the openai schema conversion is not working as expected - a single dictionary is getting returned instead of array when the slot is repeatable. This fix aims to fix that.

agent/tool - slotGroup fix

---

arklex/env/env.py

The http tool was not being correctly identified after recent refactor changes. The issue was caused by reliance on the task name rather than the intended identifier. This update corrects the identification mechanism so that the http tool is properly recognized and can be invoked as expected.
The http tool was not being correctly identified after recent refactor changes. The issue was caused by reliance on the task name rather than the intended identifier. This update corrects the identification mechanism so that the http tool is properly recognized and can be invoked as expected.
There was an issue with a check in particular and it has been sorted

api, tool: id check fix

---

arklex/env/tools/twilio/calls/transfer.py

Add an output string to twilio/calls/transfer tool
add output string to avoid error log in twilio/calls/transfer
@xinyang-articulate

add output to avoid error log in twilio/calls/transfer

---

arklex/env/tools/tools.py
arklex/orchestrator/NLU/core/slot.py
arklex/orchestrator/NLU/services/model_service.py

This PR modifies the slot filling system to combine all slots into a single schema and make one LLM call instead of processing slots individually, improving efficiency
Previously, slots were being processed individually, requiring multiple LLM calls. This was inefficient and didn't allow the LLM to see relationships between different slots. The system needed to be optimized to process all slots in a single batch operation.

api, tool: feature/one call slot fill

---

arklex/orchestrator/orchestrator.py

Ensures orchestrator uses the centralized model initialization/config (LLMConfig via ModelService). Fixes runtime error “self.llm doesn’t exist” and aligns LLM usage with project patterns.
self.llm was never initialized in AgentOrg, causing a runtime error during check_skip_node functionality; this change replaces self.llm.invoke(prompt) with self.model_service.get_response(prompt), leveraging the existing, centrally configured ModelService that respects LLMConfig to invoke the LLM consistently.

[AGML-85] fix for check skip node
